### PR TITLE
feat: add eox-audit to course xp views

### PR DESCRIPTION
**Pull request by johanv26**
## Description

feat: add eox-audit to course xp views
### Before
No eox_audit records
### After
Peek 2023-06-02 17-55

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Review by andrey-canon — CHANGES_REQUESTED** [review]
please add the requirement or add the eox-core version that includes that requirement

**Comment by johanv26** [comment]
> please add the requirement or add the eox-core version that includes that requirement

The plugin would work without eox_audit. 
https://github.com/eduNEXT/eox-nelp/pull/52/files#diff-91867b464d077443459a31c4d818308aec0a496a0c0340cec624bce0e44486c1R48-R55
Test run in the except behaviour.
so eox-audit is mandatory?

**Comment by andrey-canon** [comment]
> > please add the requirement or add the eox-core version that includes that requirement
> 
> The plugin would work without eox_audit. https://github.com/eduNEXT/eox-nelp/pull/52/files#diff-91867b464d077443459a31c4d818308aec0a496a0c0340cec624bce0e44486c1R48-R55 Tests run in the except behaviour. so eox-audit is mandatory?


you are not adding a way to use this with eox-audit, the code is there but if someone wants to use this with eox-audit-model  there is no way  to add it, so you add that to the requirements or copy the eox-core implementation that makes that optional

**Comment by johanv26** [comment]
Hi @andrey-canon I added optionally as eox-core, but also if you install the package with optional eox-audit tests running with this req would gonna fail. So I also configure the setting to avoid that error.
Also automatic tests like  machines one use base.in or test.txt (not eox-audit) there is no problem, but in our envs using audit and testing or things like that could make running `make python-test` fail due eox-audit.
So I add some configuration to avoid that.
Peek 2023-06-07 14-44

**Comment by andrey-canon** [comment]
> Hi @andrey-canon I added optionally as eox-core, but also if you install the package with optional eox-audit tests running with this req would gonna fail. So I also configure the setting to avoid that error. Also automatic tests like machines one use base.in or test.txt (not eox-audit) there is no problem, but in our envs using audit and testing or things like that could make running `make python-test` fail due eox-audit. So I add some configuration to avoid that. Peek 2023-06-07 14-44

just a question, why do you want to do that optional ?  it is not easier to add that like a simple requirement

**Comment by johanv26** [comment]
> > Hi @andrey-canon I added optionally as eox-core, but also if you install the package with optional eox-audit tests running with this req would gonna fail. So I also configure the setting to avoid that error. Also automatic tests like machines one use base.in or test.txt (not eox-audit) there is no problem, but in our envs using audit and testing or things like that could make running `make python-test` fail due eox-audit. So I add some configuration to avoid that. Peek 2023-06-07 14-44
> >       
> >         [
> >           
> >         
> >             Peek 2023-06-07 14-44
> >           ](https://user-images.githubusercontent.com/51926076/244468309-c77f52f4-f6e6-4278-a5b5-5cce8b23739e.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/51926076/244468309-c77f52f4-f6e6-4278-a5b5-5cce8b23739e.gif)
> 
> just a question, why do you want to do that optional ? it is not easier to add that like a simple requirement

Actually I like the funcionality without eox-audit installed with the decorator doing nothing. So without audit installed, the plugin works.  But I seem both options as the same, which one do you prefer?

**Comment by andrey-canon** [comment]
> > > Hi @andrey-canon I added optionally as eox-core, but also if you install the package with optional eox-audit tests running with this req would gonna fail. So I also configure the setting to avoid that error. Also automatic tests like machines one use base.in or test.txt (not eox-audit) there is no problem, but in our envs using audit and testing or things like that could make running `make python-test` fail due eox-audit. So I add some configuration to avoid that. Peek 2023-06-07 14-44
> > >       
> > >         [
> > >           
> > >             Peek 2023-06-07 14-44
> > >           
> > >         ](https://user-images.githubusercontent.com/51926076/244468309-c77f52f4-f6e6-4278-a5b5-5cce8b23739e.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/51926076/244468309-c77f52f4-f6e6-4278-a5b5-5cce8b23739e.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         Peek 2023-06-07 14-44
> > >       ](https://user-images.githubusercontent.com/51926076/244468309-c77f52f4-f6e6-4278-a5b5-5cce8b23739e.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/51926076/244468309-c77f52f4-f6e6-4278-a5b5-5cce8b23739e.gif)
> > > ```
> > 
> > 
> > just a question, why do you want to do that optional ? it is not easier to add that like a simple requirement
> 
> Actually I like the funcionality without eox-audit installed with the decorator doing nothing. So without audit installed, the plugin works. But I seem both options as the same, which one do you prefer?

I don't have any preference, just I wanted to understand why you think is better optional since that requires more work and a code that is harder to maintain

**Review by andrey-canon — APPROVED** [review]

**Pull request merged**
